services:
  Apps.challenge.controllers.CheckAddressPostController:
    class: ../../controllers/CheckAddressPostController
    arguments: ["@Challenge.Address.AddressValidator"]

  Apps.challenge.controllers.LoginPostController:
    class: ../../controllers/LoginPostController
    arguments: ["@Challenge.User.UserLogin"]

  Apps.challenge.controllers.RegisterPostController:
    class: ../../controllers/RegisterPostController
    arguments: ["@Challenge.User.UserRegister"]

  Apps.challenge.controllers.CheckWeatherGetController:
    class: ../../controllers/CheckWeatherGetController
    arguments: ["@Challenge.Weather.WeatherFinder"]

  Apps.challenge.middlewares.AuthMiddleware:
    class: ../../middlewares/AuthMiddleware
    arguments: ["@Shared.AuthConfig"]
