version: '3.8'

x-app-service: &default-app
  build: .
  command: ''
  environment:
    - MONGO_URL=mongodb://mongo:27017/dev
  depends_on:
    - mongo

  volumes:
    - .:/code:delegated
    - node_modules:/code/node_modules:delegated

services:
  app:
    <<: *default-app

  challenge:
    <<: *default-app
    command: bash -c "npm run dev:challenge"
    ports:
      - 3000:3000

  mongo:
    image: mongo

    ports:
      - 27017:27017


volumes:
  node_modules:
  esdata:
    driver: local
