imports:
  - { resource: ./application.yaml }

services:
  Challenge.RedisEnvironmentArranger:
    class: ../../../../tests/Contexts/Shared/infrastructure/redis/RedisEnvironmentArranger
    arguments: ['@Shared.ConnectionManager']

  Challenge.MongoEnvironmentArranger:
    class: ../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Shared.MongoConfig']
