imports:
  - { resource: ./Shared/application.yaml }
  - { resource: ./Address/application.yaml }
  - { resource: ./User/application.yaml }
  - { resource: ./Weather/application.yaml }
  - { resource: ./apps/application.yaml }
